services:
  - type: web
    name: zapstock-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGINS
        value: "*"
      - key: JWT_SECRET
        value: your-super-secret-jwt-key-2024-production
      - key: DATABASE_URL
        fromDatabase:
          name: zapstock-db
          property: connectionString
